import test from "node:test";
import assert from "node:assert/strict";
import {Wallet,getBytes} from "ethers";
import { Coordinator } from "../../../dist/services/coordinator/src/coordinator.js";
import {executionDigest} from "../../../dist/services/coordinator/src/signing.js";
const h=n=>`0x${n.repeat(64)}`,a=n=>`0x${n.repeat(40)}`; const p={guid:h("1"),srcEid:40161,dstEid:40231,nonce:1n,sender:h("2"),receiver:h("3"),message:"0x",payloadHash:h("4"),encodedPayloadHash:h("8"),txHash:h("5"),blockHash:h("6"),blockNumber:1n};const request={packet:p,evidence:{uri:"https://governance.example/proposal/1",digest:h("7"),observedAt:9,validUntil:100},decodedAction:"transfer 1 token",policy:"authorized proposal required"};
test("does not sign while GenLayer is pending",async()=>{let signed=0;const v={verify:async()=>["a","b"].map(provider=>({provider,blockHash:h("6"),payloadHash:h("4"),confirmations:15n}))};const g={submit:async()=>"r",finalized:async()=>undefined};const c=new Coordinator(v,g,[{address:"a",sign:async()=>{signed++;return "s"}}],1);await c.detect(request,10);await c.poll(p.guid,"r");assert.equal(signed,0);assert.equal(c.jobs.get(p.guid).snapshot.stage,"POLICY_PENDING")});
test("deduplicates detection by GUID and returns the original GenLayer request",async()=>{let submissions=0;const v={verify:async()=>["a","b"].map(provider=>({provider,blockHash:h("6"),payloadHash:h("4"),confirmations:15n}))};const g={submit:async()=>{submissions++;return "request-1"},finalized:async()=>undefined};const c=new Coordinator(v,g,[],1);assert.equal(await c.detect(request,10),"request-1");assert.equal(await c.detect(request,10),"request-1");assert.equal(submissions,1)});
test("rejects expired, future, insecure, and incomplete policy evidence",async()=>{const c=new Coordinator({verify:async()=>[]},{submit:async()=>"r",finalized:async()=>undefined},[],1);await assert.rejects(c.detect({...request,evidence:{...request.evidence,uri:"http://governance.example"}},10));await assert.rejects(c.detect({...request,evidence:{...request.evidence,validUntil:10}},10));await assert.rejects(c.detect({...request,evidence:{...request.evidence,observedAt:11}},10));await assert.rejects(c.detect({...request,decodedAction:""},10))});
test("polls every pending durable GenLayer request once",async()=>{const calls=[],verifier={verify:async()=>["a","b"].map(provider=>({provider,blockHash:h("6"),payloadHash:h("4"),confirmations:15n}))},finality={submit:async()=>h("9"),finalized:async id=>{calls.push(id);return undefined}},c=new Coordinator(verifier,finality,[],3,15n);await c.detect(request,10);assert.equal(await c.pollPending(11),1);assert.deepEqual(calls,[h("9")])});
test("confirms atomic adapter execution idempotently from quorum or verified state",async()=>{const saved=[],store={load:async()=>[],save:async record=>saved.push(record.snapshot.stage),close:()=>{}},c=new Coordinator({verify:async()=>[]},{submit:async()=>"",finalized:async()=>undefined},[],3,15n,store),guid=h("1"),job={snapshot:{stage:"QUORUM_REACHED"},markVerified(){this.snapshot.stage="VERIFIED"},markExecuted(){this.snapshot.stage="EXECUTED"}};c.jobs.set(guid,job);await c.confirmExecution(guid);assert.equal(job.snapshot.stage,"EXECUTED");assert.deepEqual(saved,["EXECUTED"]);await c.confirmExecution(guid);assert.deepEqual(saved,["EXECUTED"]);job.snapshot.stage="VERIFIED";await c.confirmExecution(guid);assert.equal(job.snapshot.stage,"EXECUTED")});
test("collects authorization without overstating state and records only the durable quorum",async()=>{
  const wallets=[1,2,3,4,5].map(value=>new Wallet(`0x${value.toString(16).padStart(64,"0")}`)).sort((left,right)=>left.address.toLowerCase().localeCompare(right.address.toLowerCase())),authorized=wallets.map(wallet=>wallet.address.toLowerCase()),envelope={chainId:421614n,adapter:a("6"),verificationTarget:a("7"),guid:p.guid,packetDigest:p.payloadHash,evidenceDigest:request.evidence.digest,callData:"0x1234",expiry:50n},digest=executionDigest(envelope),signers=wallets.map((wallet,index)=>({address:authorized[index],sign:async()=>({address:authorized[index],digest,signature:await wallet.signMessage(getBytes(digest))})})),verifier={verify:async()=>["a","b"].map(provider=>({provider,blockHash:h("6"),payloadHash:h("4"),confirmations:15n}))},result={guid:p.guid,packetDigest:p.payloadHash,evidenceDigest:request.evidence.digest,decision:"ALLOW",reasonCode:"AUTHORIZED",finalizedAt:10,policyVersion:"v1"},finality={submit:async()=>"r",finalized:async()=>result},saved=[],store={load:async()=>[],save:async record=>saved.push(record.snapshot.stage),close:()=>{}},c=new Coordinator(verifier,finality,signers,3,15n,store);
  await c.detect(request,10);await c.poll(p.guid,"r",10);const shares=await c.collectAuthorization(p.guid,envelope,authorized);assert.equal(shares.length,3);assert.equal(c.jobs.get(p.guid).snapshot.stage,"POLICY_FINALIZED");assert.deepEqual(c.jobs.get(p.guid).snapshot.signers,[]);await c.recordQuorum(p.guid,shares.map(share=>share.address));assert.equal(c.jobs.get(p.guid).snapshot.stage,"QUORUM_REACHED");const saves=saved.length;await c.recordQuorum(p.guid,shares.map(share=>share.address));assert.equal(saved.length,saves);await assert.rejects(c.recordQuorum(p.guid,[shares[0].address,shares[1].address,authorized[3]]),/mismatch/);
});
test("rolls back in-memory quorum when durable persistence fails",async()=>{const c=new Coordinator({verify:async()=>[]},{submit:async()=>"",finalized:async()=>undefined},[],3,15n,{load:async()=>[],save:async()=>{throw new Error("disk full")},close:()=>{}}),job={snapshot:{stage:"POLICY_FINALIZED",signers:[]},addSigner(address,quorum){this.snapshot.signers.push(address);if(this.snapshot.signers.length>=quorum)this.snapshot.stage="QUORUM_REACHED"}};c.jobs.set(h("1"),job);await assert.rejects(c.recordQuorum(h("1"),[a("1"),a("2"),a("3")]),/disk full/);assert.equal(job.snapshot.stage,"POLICY_FINALIZED");assert.deepEqual(job.snapshot.signers,[])});
test("rolls back in-memory execution when its durable write fails",async()=>{const c=new Coordinator({verify:async()=>[]},{submit:async()=>"",finalized:async()=>undefined},[],3,15n,{load:async()=>[],save:async()=>{throw new Error("disk full")},close:()=>{}}),job={snapshot:{stage:"QUORUM_REACHED",signers:[a("1"),a("2"),a("3")]},markVerified(){this.snapshot.stage="VERIFIED"},markExecuted(){this.snapshot.stage="EXECUTED"}};c.jobs.set(h("1"),job);await assert.rejects(c.confirmExecution(h("1")),/disk full/);assert.equal(job.snapshot.stage,"QUORUM_REACHED")});
