import test from"node:test";
import assert from"node:assert/strict";
import fs,{mkdtempSync,rmSync}from"node:fs";
import{tmpdir}from"node:os";
import{join}from"node:path";
import{ContractFactory,Interface,Wallet,getBytes,id,keccak256,sha256,toUtf8Bytes,zeroPadValue}from"ethers";
import{decodePacketV1}from"../../../dist/packages/core/src/packet-v1.js";
import{SentinelJob}from"../../../dist/packages/core/src/state-machine.js";
import{Coordinator}from"../../../dist/services/coordinator/src/coordinator.js";
import{DeliveryPlanner}from"../../../dist/services/coordinator/src/delivery-planner.js";
import{DestinationWorker}from"../../../dist/services/coordinator/src/destination-worker.js";
import{LocalEdrDestinationVerifier,LocalEdrPathVerifier,LocalOAppExecutionConfirmer}from"../../../dist/services/coordinator/src/local-demo-proofs.js";
import{OperatorRecoveryService}from"../../../dist/services/coordinator/src/operator-recovery.js";
import{recoveryTypedData}from"../../../dist/services/coordinator/src/recovery-proposal.js";
import{SqliteRecoveryStore}from"../../../dist/services/coordinator/src/recovery-store.js";
import{SqliteRuntimeLease}from"../../../dist/services/coordinator/src/runtime-lease.js";
import{IsolatedSignerService}from"../../../dist/services/coordinator/src/signing.js";
import{Uln302IntentFactory}from"../../../dist/services/coordinator/src/uln302-intent.js";
import{SqliteVerificationOutbox}from"../../../dist/services/coordinator/src/verification-outbox.js";
import{startLocalEvm}from"../../../contracts/test/local-evm.js";

const artifact=name=>JSON.parse(fs.readFileSync(`dist/contracts/${name}.json`,"utf8"));
const a=value=>`0x${value.repeat(40)}`,h=value=>`0x${value.repeat(64)}`;
const recordInterface=new Interface(["function record(bytes32)"]);
async function deploy(name,signer,...args){const value=artifact(name),contract=await new ContractFactory(value.abi,value.evm.bytecode.object,signer).deploy(...args);await contract.waitForDeployment();return contract}

test("recovers one real ambiguous adapter transaction once through timelocked 3-of-5 proof",async t=>{
  const evm=await startLocalEvm(14);t.after(evm.close);
  const directory=mkdtempSync(join(tmpdir(),"sentinel-recovery-e2e-")),databasePath=join(directory,"state.db");t.after(()=>rmSync(directory,{recursive:true,force:true}));
  const[deployer,sourceOwner,destinationOwner,targetOwner,submitter]=evm.signers;
  const sourceEndpoint=await deploy("MockEndpointV2",deployer,40161),destinationEndpoint=await deploy("MockEndpointV2",deployer,40231);
  const source=await deploy("TreasuryPolicyOApp",sourceOwner,await sourceEndpoint.getAddress(),await sourceOwner.getAddress());
  const destination=await deploy("TreasuryPolicyOApp",destinationOwner,await destinationEndpoint.getAddress(),await destinationOwner.getAddress());
  const actionTarget=await deploy("ActionTarget",targetOwner),verificationTarget=await deploy("MockVerificationTarget",deployer);
  const signerRecords=await Promise.all(evm.signers.slice(5,10).map(async signer=>({signer,address:(await signer.getAddress()).toLowerCase()})));signerRecords.sort((left,right)=>left.address.localeCompare(right.address));
  const authorizedSigners=signerRecords.map(value=>value.address);
  const adapter=await deploy("SentinelDVNAdapter",deployer,await destinationEndpoint.getAddress(),await verificationTarget.getAddress(),40231,authorizedSigners,3),adapterAddress=(await adapter.getAddress()).toLowerCase();
  await(await sourceEndpoint.setOptionalDvn(adapterAddress)).wait();await(await destinationEndpoint.setOptionalDvn(adapterAddress)).wait();
  const sourcePeer=zeroPadValue(await source.getAddress(),32),destinationPeer=zeroPadValue(await destination.getAddress(),32);
  await(await source.connect(sourceOwner).setPeer(40231,destinationPeer)).wait();await(await destination.connect(destinationOwner).setPeer(40161,sourcePeer)).wait();
  await(await source.connect(sourceOwner).setAuthorizedTarget(await actionTarget.getAddress(),true)).wait();await(await destination.connect(destinationOwner).setAuthorizedTarget(await actionTarget.getAddress(),true)).wait();
  const approvedArgument=id("approved"),action={authorizationId:id("authorization"),target:await actionTarget.getAddress(),value:0n,data:recordInterface.encodeFunctionData("record",[approvedArgument])};
  const quote=await source.quoteAction(40231,action,"0x",false),fee={nativeFee:quote.nativeFee,lzTokenFee:quote.lzTokenFee};
  const sourceTransaction=await source.connect(sourceOwner).sendAction(40231,action,"0x",fee,{value:fee.nativeFee}),sourceReceipt=await sourceTransaction.wait();
  const sent=sourceReceipt.logs.map(log=>{try{return sourceEndpoint.interface.parseLog(log)}catch{return null}}).find(log=>log?.name==="PacketSent");assert.ok(sent);
  const decoded=decodePacketV1(sent.args.encodedPayload),packet={guid:decoded.guid,srcEid:decoded.srcEid,dstEid:decoded.dstEid,nonce:decoded.nonce,sender:decoded.sender,receiver:decoded.receiver,message:decoded.message,payloadHash:decoded.payloadHash,encodedPayloadHash:keccak256(sent.args.encodedPayload),txHash:sourceTransaction.hash,blockHash:sourceReceipt.blockHash,blockNumber:BigInt(sourceReceipt.blockNumber)};
  const evidenceDigest=sha256(toUtf8Bytes('{"status":"AUTHORIZED"}')),request={packet,evidence:{uri:"https://governance.fixture.invalid/authorization",digest:evidenceDigest,observedAt:1,validUntil:9999999999},decodedAction:JSON.stringify({authorizationId:action.authorizationId,target:action.target.toLowerCase(),value:"0",selector:action.data.slice(0,10),calldata:action.data}),policy:"exact authorization required"},latest=await evm.provider.getBlock("latest"),policyNow=Number(latest.timestamp),result={guid:packet.guid,packetDigest:packet.payloadHash,evidenceDigest,decision:"ALLOW",reasonCode:"LOCAL_FIXTURE_ALLOW",finalizedAt:policyNow,policyVersion:"local-demo-v1"};
  const verificationTargetAddress=await verificationTarget.getAddress(),signerServices=signerRecords.map(value=>new IsolatedSignerService({address:value.address,signMessageDigest:digest=>value.signer.signMessage(getBytes(digest))},{assertFinalized:async observed=>assert.equal(observed.decision,"ALLOW")},{chainId:31337n,adapter:adapterAddress,verificationTarget:verificationTargetAddress,maxTtlSeconds:300n},()=>BigInt(policyNow)));
  const coordinator=new Coordinator({verify:async()=>[]},{submit:async()=>"",finalized:async()=>undefined},signerServices,3);coordinator.requests.set(packet.guid,request);coordinator.jobs.set(packet.guid,SentinelJob.restore({packet,stage:"POLICY_FINALIZED",verifications:[],signers:[],result}));
  const requiredDvn=(await evm.signers[10].getAddress()).toLowerCase(),rpc=(method,params)=>evm.provider.send(method,params),pathVerifier=new LocalEdrPathVerifier(rpc,{chainId:31337n,srcEid:40161,endpoint:await destinationEndpoint.getAddress(),receiveLibrary:await verificationTarget.getAddress(),oapp:await destination.getAddress(),adapter:adapterAddress,sourcePeer,confirmations:1n,requiredDvns:[requiredDvn],optionalDvns:[adapterAddress],optionalDvnThreshold:1,authorizedSigners,quorum:3});
  const outbox=new SqliteVerificationOutbox(databasePath,authorizedSigners,3),recoveryStore=new SqliteRecoveryStore(databasePath),lease=new SqliteRuntimeLease(databasePath,60);t.after(()=>{lease.close();recoveryStore.close();outbox.close()});
  const planner=new DeliveryPlanner(coordinator,outbox,pathVerifier,new Uln302IntentFactory(300),authorizedSigners,assert.fail,()=>policyNow);await planner.pollOnce();assert.equal((await outbox.get(packet.guid)).state,"READY");
  const execution=new LocalOAppExecutionConfirmer(coordinator,rpc,{from:await evm.signers[11].getAddress(),endpoint:await destinationEndpoint.getAddress(),oapp:await destination.getAddress(),actionTarget:await actionTarget.getAddress()});
  let candidateTransactionHash,submissionCount=0;
  const submitterAdapter={used:digest=>adapter.used(digest),async submitVerification(envelope,signatures){submissionCount++;const transaction=await adapter.connect(submitter).submitVerification(envelope.guid,envelope.packetDigest,envelope.evidenceDigest,envelope.callData,envelope.expiry,signatures);candidateTransactionHash=transaction.hash.toLowerCase();await transaction.wait();throw new Error("ambiguous provider response")}};
  const destinationVerifier=new LocalEdrDestinationVerifier(rpc,adapterAddress,1n),worker=new DestinationWorker(outbox,submitterAdapter,destinationVerifier,pathVerifier,execution,assert.fail,()=>policyNow+1);
  await worker.pollOnce();const ambiguous=await outbox.get(packet.guid);assert.equal(ambiguous.state,"RECOVERY_REQUIRED");assert.equal(ambiguous.failureCode,"SUBMISSION_AMBIGUOUS");assert.equal(submissionCount,1);assert.match(candidateTransactionHash,/^0x[0-9a-f]{64}$/);
  const recoveryWallets=[20,21,22,23,24].map(value=>new Wallet(`0x${value.toString(16).padStart(64,"0")}`)).sort((left,right)=>left.address.toLowerCase().localeCompare(right.address.toLowerCase())),recoveryOperators=recoveryWallets.map(value=>value.address.toLowerCase());
  const config={pathway:{name:"local-recovery",sourceChainId:31337,destinationChainId:31337,srcEid:40161,dstEid:40231,endpoint:await sourceEndpoint.getAddress(),sendLibrary:await sourceEndpoint.getAddress(),sourceOAppAddress:await source.getAddress(),sourceOApp:sourcePeer,destinationOApp:destinationPeer,sentinelDvn:adapterAddress,requiredDvns:[requiredDvn],optionalDvns:[adapterAddress],confirmations:1n},destination:{chainId:31337,srcEid:40161,endpoint:await destinationEndpoint.getAddress(),receiveLibrary:await verificationTarget.getAddress(),oapp:await destination.getAddress(),adapter:adapterAddress,authorizedSigners},genlayer:{policyContract:await source.getAddress()},recovery:{operators:recoveryOperators,quorum:3,minimumDelaySeconds:900,maximumLifetimeSeconds:3600}};
  let recoveryNow=Number((await evm.provider.getBlock("latest")).timestamp);
  const recovery=new OperatorRecoveryService({config,recoveryStore,inbox:{},outbox,sourceVerifier:{},destinationPath:pathVerifier,destinationVerifier,lease,now:()=>recoveryNow,nonce:()=>h("e")});
  const proposal=await recovery.prepareDestination(packet.guid,candidateTransactionHash),typed=recoveryTypedData(config,proposal),approvals=await Promise.all(recoveryWallets.slice(0,3).map(async wallet=>({address:wallet.address.toLowerCase(),signature:await wallet.signTypedData(typed.domain,typed.types,typed.value)})));approvals.sort((left,right)=>left.address.localeCompare(right.address));
  recoveryNow+=900;const bundle={proposal,approvals},receipt=await recovery.apply(bundle);
  assert.equal((await outbox.get(packet.guid)).state,"CONFIRMED");assert.equal(submissionCount,1);assert.equal((await outbox.listRecoveryReceipts()).length,1);assert.equal(receipt.resultCode,"DESTINATION_CONFIRMED");
  await worker.pollOnce();assert.equal(coordinator.jobs.get(packet.guid).snapshot.stage,"EXECUTED");assert.equal(await destination.executedGuid(packet.guid),true);assert.equal(await actionTarget.recorded(),approvedArgument);assert.equal(submissionCount,1);
  assert.deepEqual(await recovery.apply(bundle),receipt);assert.equal((await outbox.listRecoveryReceipts()).length,1);assert.equal(submissionCount,1);
});
