import test from "node:test";
import assert from "node:assert/strict";
import {SentinelRuntime} from "../../../dist/services/coordinator/src/runtime.js";

const deferred=()=>{let resolve;const promise=new Promise(done=>{resolve=done});return{promise,resolve}};
function setup(overrides={}){const calls=[],scheduled=[];let cancelled=0;const dependencies={restore:async()=>calls.push("restore"),ingest:async()=>calls.push("ingest"),pollFinality:async()=>calls.push("finality"),planDeliveries:async()=>calls.push("plan-deliveries"),deliver:async()=>calls.push("deliver"),listen:async()=>calls.push("listen"),claimLease:async()=>calls.push("claim-lease"),heartbeatLease:async()=>calls.push("heartbeat-lease"),releaseLease:async()=>calls.push("release-lease"),closeServer:async()=>calls.push("close-server"),closeStores:()=>calls.push("close-stores"),report:error=>calls.push(`error:${error.message}`),intervalMs:1000,schedule:task=>{scheduled.push(task);return()=>{cancelled++}},...overrides};return{runtime:new SentinelRuntime(dependencies),calls,scheduled,cancelled:()=>cancelled}}

test("restores and listens before claiming the lease and heartbeats around each tick",async()=>{const value=setup();await value.runtime.start();assert.deepEqual(value.calls,["restore","listen","claim-lease"]);assert.equal(value.scheduled.length,1);await value.scheduled[0]();assert.deepEqual(value.calls,["restore","listen","claim-lease","heartbeat-lease","ingest","finality","plan-deliveries","deliver","heartbeat-lease"]);assert.deepEqual(value.runtime.status,{started:true,stopping:false,tickActive:false})});
test("prevents overlapping ticks and reports errors without stopping",async()=>{const gate=deferred(),errors=[],value=setup({ingest:async()=>gate.promise,report:error=>errors.push(error.message)});await value.runtime.start();const first=value.scheduled[0](),second=value.scheduled[0]();assert.equal(value.runtime.status.tickActive,true);gate.resolve();await Promise.all([first,second]);assert.equal(value.calls.filter(call=>call==="finality").length,1);const failing=setup({ingest:async()=>{throw new Error("RPC down")},report:error=>errors.push(error.message)});await failing.runtime.start();await failing.scheduled[0]();assert.deepEqual(errors,["RPC down"]);assert.equal(failing.runtime.status.started,true)});
test("retries a failed planning phase on the next tick without running delivery early",async()=>{let fail=true;const value=setup({planDeliveries:async()=>{value.calls.push("plan-deliveries");if(fail)throw new Error("signers unavailable")}});await value.runtime.start();await value.scheduled[0]();assert.deepEqual(value.calls,["restore","listen","claim-lease","heartbeat-lease","ingest","finality","plan-deliveries","error:signers unavailable","heartbeat-lease"]);fail=false;await value.scheduled[0]();assert.deepEqual(value.calls.slice(-5),["ingest","finality","plan-deliveries","deliver","heartbeat-lease"])});
test("idempotent stop cancels scheduling, drains work, closes HTTP, releases the lease, then stores",async()=>{const gate=deferred(),value=setup({ingest:async()=>gate.promise});await value.runtime.start();const tick=value.scheduled[0]();const stopping=value.runtime.stop();assert.deepEqual(value.calls,["restore","listen","claim-lease","heartbeat-lease"]);gate.resolve();await tick;await stopping;await value.runtime.stop();assert.deepEqual(value.calls,["restore","listen","claim-lease","heartbeat-lease","finality","plan-deliveries","deliver","heartbeat-lease","close-server","release-lease","close-stores"]);assert.equal(value.cancelled(),1);assert.deepEqual(value.runtime.status,{started:false,stopping:false,tickActive:false})});
test("startup failure after binding closes resources without releasing an unclaimed lease",async()=>{const value=setup({claimLease:async()=>{value.calls.push("claim-lease");throw new Error("runtime active")}});await assert.rejects(value.runtime.start(),/runtime active/);assert.deepEqual(value.calls,["restore","listen","claim-lease","close-server","close-stores"]);assert.deepEqual(value.runtime.status,{started:false,stopping:false,tickActive:false})});
