import test from "node:test";import assert from "node:assert/strict";import {Wallet,getBytes} from "ethers";import {collectQuorum,executionDigest,IsolatedSignerService,submitVerificationOnce} from "../../../dist/services/coordinator/src/signing.js";
const h=n=>`0x${n.repeat(64)}`,adapter="0x1111111111111111111111111111111111111111",target="0x2222222222222222222222222222222222222222";const envelope={chainId:421614n,adapter,verificationTarget:target,guid:h("1"),packetDigest:h("4"),evidenceDigest:h("7"),callData:"0x1234",expiry:200n};const result={guid:h("1"),packetDigest:h("4"),evidenceDigest:h("7"),decision:"ALLOW",reasonCode:"GENLAYER_FINALIZED_ALLOW",finalizedAt:100,policyVersion:"v1"},authorization={witness:{transactionId:h("9"),evidenceUri:"https://governance.example/proposal/1",decodedAction:"transfer 1 token",policy:"authorization required"},result};
function service(wallet,finality={assertFinalized:async()=>{}},clock=()=>100n){return new IsolatedSignerService({address:wallet.address,signMessageDigest:async d=>wallet.signMessage(getBytes(d))},finality,{chainId:421614n,adapter,verificationTarget:target,maxTtlSeconds:120n},clock)}
test("collects only authorized valid shares and sorts them for the adapter",async()=>{const wallets=[Wallet.createRandom(),Wallet.createRandom(),Wallet.createRandom()];let checks=0;const services=wallets.map(w=>service(w,{assertFinalized:async(observedEnvelope,observedAuthorization)=>{checks++;assert.equal(observedEnvelope,envelope);assert.equal(observedAuthorization,authorization)}}));const shares=await collectQuorum(envelope,authorization,services,wallets.map(w=>w.address),2);assert.equal(shares.length,2);assert.equal(checks,3);assert.equal(shares[0].digest,executionDigest(envelope));assert.ok(shares[0].address.toLowerCase()<shares[1].address.toLowerCase())});
test("each signer fails closed on finality, decision, domain, binding, and expiry",async()=>{const wallet=Wallet.createRandom(),denied={...authorization,result:{...result,decision:"DENY",reasonCode:"GENLAYER_FINALIZED_DENY"}};await assert.rejects(service(wallet).sign(envelope,denied));await assert.rejects(service(wallet,{assertFinalized:async()=>{throw new Error("not final")}}).sign(envelope,authorization));await assert.rejects(service(wallet).sign({...envelope,adapter:"0x3333333333333333333333333333333333333333"},authorization));await assert.rejects(service(wallet).sign({...envelope,guid:h("9")},authorization));await assert.rejects(service(wallet,undefined,()=>200n).sign(envelope,authorization))});
test("rejects changed authorization binding before attestor or key invocation",async()=>{const wallet=Wallet.createRandom();let attestations=0,keys=0;const value=new IsolatedSignerService({address:wallet.address,signMessageDigest:async digest=>{keys++;return wallet.signMessage(getBytes(digest))}},{assertFinalized:async()=>{attestations++}},{chainId:421614n,adapter,verificationTarget:target,maxTtlSeconds:120n},()=>100n);await assert.rejects(value.sign(envelope,{...authorization,result:{...result,guid:h("0")}}),/binding/);assert.equal(attestations,0);assert.equal(keys,0)});
test("submits once and verifies destination idempotency",async()=>{const wallet=Wallet.createRandom();const share=await service(wallet).sign(envelope,authorization);let used=false,calls=0;const client={used:async()=>used,submitVerification:async()=>{calls++;used=true;return h("a")}};assert.deepEqual(await submitVerificationOnce(client,envelope,[share]),{status:"SUBMITTED",txHash:h("a")});assert.deepEqual(await submitVerificationOnce(client,envelope,[share]),{status:"ALREADY_VERIFIED"});assert.equal(calls,1)});
test("rejects a destination that does not persist verification",async()=>{const share=await service(Wallet.createRandom()).sign(envelope,authorization);const client={used:async()=>false,submitVerification:async()=>h("a")};await assert.rejects(submitVerificationOnce(client,envelope,[share]))});
test("counts unique authorized remote identities during partial outage",async()=>{const wallets=[Wallet.createRandom(),Wallet.createRandom(),Wallet.createRandom()],share=async wallet=>service(wallet).sign(envelope,authorization),services=[{address:wallets[0].address,sign:async()=>share(wallets[0])},{address:wallets[1].address,sign:async()=>share(wallets[1])},{address:wallets[1].address,sign:async()=>share(wallets[1])},{address:wallets[2].address,sign:async()=>{throw new Error("offline")}}],authorized=wallets.map(wallet=>wallet.address);assert.equal((await collectQuorum(envelope,authorization,services,authorized,2)).length,2);await assert.rejects(collectQuorum(envelope,authorization,services,authorized,3),/quorum/)});
test("rejects a share whose recovered or responding identity does not match",async()=>{const wallets=[Wallet.createRandom(),Wallet.createRandom(),Wallet.createRandom()],digest=executionDigest(envelope),signed=async wallet=>wallet.signMessage(getBytes(digest)),services=[{address:wallets[0].address,sign:async()=>({address:wallets[0].address,digest,signature:await signed(wallets[1])})},{address:wallets[1].address,sign:async()=>({address:wallets[2].address,digest,signature:await signed(wallets[2])})}];await assert.rejects(collectQuorum(envelope,authorization,services,wallets.map(wallet=>wallet.address),2),/quorum/)});
