import test from "node:test";
import assert from "node:assert/strict";
import fs,{mkdtempSync,rmSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {ContractFactory,concat,getBytes,keccak256,solidityPackedKeccak256} from "ethers";
import {encodePacketV1} from "../../../dist/packages/core/src/packet-v1.js";
import {SentinelJob} from "../../../dist/packages/core/src/state-machine.js";
import {Coordinator} from "../../../dist/services/coordinator/src/coordinator.js";
import {DeliveryPlanner} from "../../../dist/services/coordinator/src/delivery-planner.js";
import {IndependentDestinationVerifier} from "../../../dist/services/coordinator/src/destination-verifier.js";
import {DestinationWorker} from "../../../dist/services/coordinator/src/destination-worker.js";
import {IsolatedSignerService} from "../../../dist/services/coordinator/src/signing.js";
import {Uln302IntentFactory} from "../../../dist/services/coordinator/src/uln302-intent.js";
import {SqliteVerificationOutbox} from "../../../dist/services/coordinator/src/verification-outbox.js";
import {startLocalEvm} from "../../../contracts/test/local-evm.js";

const artifact=name=>JSON.parse(fs.readFileSync(`dist/contracts/${name}.json`,"utf8"));
const a=n=>`0x${n.repeat(40)}`,h=n=>`0x${n.repeat(64)}`,b=n=>`0x${"0".repeat(24)}${n.repeat(40)}`;

function policy(now,decision="ALLOW"){
  const nonce=1n,srcEid=40161,dstEid=40231,sender=h("2"),receiver=b("4"),message="0x1234",guid=solidityPackedKeccak256(["uint64","uint32","bytes32","uint32","bytes32"],[nonce,srcEid,sender,dstEid,receiver]),payloadHash=keccak256(concat([guid,message])),encoded=encodePacketV1({nonce,srcEid,sender,dstEid,receiver,guid,message}),packet={guid,srcEid,dstEid,nonce,sender,receiver,message,payloadHash,encodedPayloadHash:keccak256(encoded),txHash:h("5"),blockHash:h("6"),blockNumber:10n},evidence={uri:"https://governance.example/auth",digest:h("7"),observedAt:now-10,validUntil:now+600},request={packet,evidence,decodedAction:"authorized action",policy:"exact authorization"},result={guid,packetDigest:payloadHash,evidenceDigest:evidence.digest,decision,reasonCode:`GENLAYER_FINALIZED_${decision}`,finalizedAt:now,policyVersion:"v1"};return{request,result}}

test("executes finalized ALLOW through durable 3-of-5 quorum and independently confirmed ULN302 delivery while DENY stays inert",async t=>{
  const evm=await startLocalEvm(8);t.after(evm.close);const dir=mkdtempSync(join(tmpdir(),"sentinel-e2e-"));t.after(()=>rmSync(dir,{recursive:true,force:true}));
  const latest=await evm.provider.getBlock("latest"),now=Number(latest.timestamp),targetArtifact=artifact("MockVerificationTarget"),target=await new ContractFactory(targetArtifact.abi,targetArtifact.evm.bytecode.object,evm.signers[0]).deploy();await target.waitForDeployment();
  const signerRecords=await Promise.all(evm.signers.slice(2,7).map(async signer=>({signer,address:(await signer.getAddress()).toLowerCase()})));signerRecords.sort((left,right)=>left.address.localeCompare(right.address));const authorized=signerRecords.map(record=>record.address),adapterArtifact=artifact("SentinelDVNAdapter"),targetAddress=await target.getAddress(),adapter=await new ContractFactory(adapterArtifact.abi,adapterArtifact.evm.bytecode.object,evm.signers[1]).deploy(await evm.signers[0].getAddress(),targetAddress,40231,authorized,3);await adapter.waitForDeployment();const adapterAddress=await adapter.getAddress();
  const requestId=h("9");let finalityChecks=0,signerCalls=0;const services=signerRecords.map((record,index)=>new IsolatedSignerService({address:record.address,signMessageDigest:async digest=>{signerCalls++;return record.signer.signMessage(getBytes(digest))}},{assertFinalized:async(envelope,authorization)=>{finalityChecks++;assert.equal(envelope.guid,authorization.result.guid);assert.equal(authorization.witness.evidenceUri,"https://governance.example/auth");assert.equal(authorization.witness.decodedAction,"authorized action");assert.equal(authorization.witness.policy,"exact authorization");if(index===3)throw new Error("independent signer unavailable");const independentlyObservedTransactionId=index===4?h("8"):requestId;if(authorization.witness.transactionId!==independentlyObservedTransactionId)throw new Error("independent GenLayer transaction mismatch")}},{chainId:31337n,adapter:adapterAddress,verificationTarget:targetAddress,maxTtlSeconds:300n},()=>BigInt(now)));
  const value=policy(now),coordinator=new Coordinator({verify:async()=>[]},{submit:async()=>"",finalized:async()=>undefined},services,3);coordinator.jobs.set(value.request.packet.guid,SentinelJob.restore({packet:value.request.packet,stage:"POLICY_FINALIZED",verifications:[],signers:[],result:value.result}));coordinator.requests.set(value.request.packet.guid,value.request);coordinator.requestIds.set(value.request.packet.guid,requestId);
  const path={observedBlockNumber:1n,observedBlockHash:h("d"),chainId:31337n,srcEid:40161,endpoint:a("7"),receiveLibrary:targetAddress,oapp:a("4"),adapter:adapterAddress,confirmations:1n,requiredDvns:[a("a")],optionalDvns:[adapterAddress.toLowerCase()],optionalDvnThreshold:1,authorizedSigners:authorized,quorum:3,configurationDigest:h("c")},pathVerifier={verify:async()=>path},outbox=new SqliteVerificationOutbox(join(dir,"state.db"),authorized,3),reports=[],planner=new DeliveryPlanner(coordinator,outbox,pathVerifier,new Uln302IntentFactory(300),authorized,error=>reports.push(error),()=>now);
  await planner.pollOnce();assert.equal((await outbox.get(value.request.packet.guid)).state,"READY");assert.equal(coordinator.jobs.get(value.request.packet.guid).snapshot.stage,"QUORUM_REACHED");assert.equal(signerCalls,3);assert.equal(finalityChecks,5);
  const submitter={used:digest=>adapter.used(digest),async submitVerification(envelope,signatures){const tx=await adapter.connect(evm.signers[7]).submitVerification(envelope.guid,envelope.packetDigest,envelope.evidenceDigest,envelope.callData,envelope.expiry,signatures);return tx.hash}},receiptRpc=async(_url,method,params)=>evm.provider.send(method,params),receiptVerifier=new IndependentDestinationVerifier(["https://receipt-a.example","https://receipt-b.example"],adapterAddress,1n,receiptRpc),worker=new DestinationWorker(outbox,submitter,receiptVerifier,pathVerifier,coordinator,error=>reports.push(error),()=>now+1);
  await worker.pollOnce();assert.equal((await outbox.get(value.request.packet.guid)).state,"SUBMITTED");await worker.pollOnce();assert.equal((await outbox.get(value.request.packet.guid)).state,"CONFIRMED");assert.equal(coordinator.jobs.get(value.request.packet.guid).snapshot.stage,"EXECUTED");assert.equal(await target.lastPayloadHash(),value.request.packet.payloadHash);assert.equal(await target.lastConfirmations(),1n);assert.equal(getBytes(await target.lastHeader()).length,81);assert.deepEqual(reports,[]);
  let limitedFinalityChecks=0,limitedSignerCalls=0;const limitedServices=signerRecords.map((record,index)=>new IsolatedSignerService({address:record.address,signMessageDigest:async digest=>{limitedSignerCalls++;return record.signer.signMessage(getBytes(digest))}},{assertFinalized:async()=>{limitedFinalityChecks++;if(index>1)throw new Error("independent signer refuses authorization")}},{chainId:31337n,adapter:adapterAddress,verificationTarget:targetAddress,maxTtlSeconds:300n},()=>BigInt(now))),limitedCoordinator=new Coordinator({verify:async()=>[]},{submit:async()=>"",finalized:async()=>undefined},limitedServices,3);limitedCoordinator.jobs.set(value.request.packet.guid,SentinelJob.restore({packet:value.request.packet,stage:"POLICY_FINALIZED",verifications:[],signers:[],result:value.result}));limitedCoordinator.requests.set(value.request.packet.guid,value.request);limitedCoordinator.requestIds.set(value.request.packet.guid,requestId);const limitedOutbox=new SqliteVerificationOutbox(join(dir,"limited.db"),authorized,3),limitedReports=[],limitedPlanner=new DeliveryPlanner(limitedCoordinator,limitedOutbox,pathVerifier,new Uln302IntentFactory(300),authorized,error=>limitedReports.push(error),()=>now),adapterNonceBefore=await evm.provider.getTransactionCount(await evm.signers[7].getAddress());await limitedPlanner.pollOnce();assert.equal((await limitedOutbox.get(value.request.packet.guid)).state,"SIGNING");assert.equal(limitedCoordinator.jobs.get(value.request.packet.guid).snapshot.stage,"POLICY_FINALIZED");assert.equal(limitedFinalityChecks,5);assert.equal(limitedSignerCalls,2);assert.equal(limitedReports.length,1);assert.match(String(limitedReports[0]),/quorum/);assert.equal(await evm.provider.getTransactionCount(await evm.signers[7].getAddress()),adapterNonceBefore);limitedOutbox.close();
  const denied=policy(now,"DENY"),deniedCoordinator=new Coordinator({verify:async()=>[]},{submit:async()=>"",finalized:async()=>undefined},services,3);deniedCoordinator.jobs.set(denied.request.packet.guid,SentinelJob.restore({packet:denied.request.packet,stage:"REJECTED",verifications:[],signers:[],result:denied.result}));deniedCoordinator.requests.set(denied.request.packet.guid,denied.request);const deniedOutbox=new SqliteVerificationOutbox(join(dir,"denied.db"),authorized,3),deniedPlanner=new DeliveryPlanner(deniedCoordinator,deniedOutbox,pathVerifier,new Uln302IntentFactory(300),authorized,error=>reports.push(error),()=>now),nonceBefore=await evm.provider.getTransactionCount(await evm.signers[7].getAddress());assert.equal(await deniedPlanner.pollOnce(),0);assert.equal(await deniedOutbox.get(denied.request.packet.guid),undefined);assert.equal(await evm.provider.getTransactionCount(await evm.signers[7].getAddress()),nonceBefore);assert.equal(signerCalls,3);deniedOutbox.close();outbox.close();
});
