import {deliveryTimelineIndex} from "./timeline.js";
const stages=["Packet detected","RPC confirmations","GenLayer consensus","GenLayer finality","Signing intent","Signer quorum","Destination submission","LayerZero verification","OApp execution"],stageIndex={DETECTED:0,CONFIRMED:1,POLICY_PENDING:2,POLICY_FINALIZED:3,QUORUM_REACHED:5,VERIFIED:7,EXECUTED:8,REJECTED:3};
const timeline=document.querySelector("#timeline"),status=document.querySelector("#connection-status"),notice=document.querySelector("#live-notice"),select=document.querySelector("#job-select"),inspector=document.querySelector("#inspector"),refreshed=document.querySelector("#refresh-time"),runtimeMode=document.querySelector("#runtime-mode");
let jobs=[],selectedGuid,observedGuid,deliveryByGuid=new Map();
const short=value=>typeof value==="string"&&value.length>22?`${value.slice(0,10)}…${value.slice(-8)}`:String(value??"—");
const text=(parent,label,value)=>{const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=label;dd.textContent=String(value??"—");dd.title=String(value??"");parent.append(dt,dd)};
function renderTimeline(job){const delivery=deliveryByGuid.get(job.packet.guid.toLowerCase()),deliveryIndex=deliveryTimelineIndex(delivery),current=Math.max(stageIndex[job.stage]??0,deliveryIndex??0),incident=job.stage==="REJECTED"||delivery?.state==="FAILED"||delivery?.state==="RECOVERY_REQUIRED";timeline.replaceChildren(...stages.map((label,index)=>{const el=document.createElement("div");el.className=`step ${index<current?"complete":index===current?(incident?"rejected":"current"):""}`;const n=document.createElement("span");n.textContent=String(index+1).padStart(2,"0");const box=document.createElement("div"),strong=document.createElement("strong"),small=document.createElement("small");strong.textContent=label;small.textContent=index<current?"Complete":index===current?(delivery&&deliveryIndex===current?delivery.state.replaceAll("_"," ").toLowerCase():job.stage==="REJECTED"?"Rejected":job.stage.replaceAll("_"," ").toLowerCase()):"Not started";box.append(strong,small);el.append(n,box);return el}))}
function renderInspector(job){inspector.hidden=false;const packet=document.querySelector("#packet-details");packet.replaceChildren();for(const [label,value] of [["GUID",job.packet.guid],["Pathway",`${job.packet.srcEid} → ${job.packet.dstEid}`],["Nonce",job.packet.nonce],["Transaction",job.packet.txHash],["Block",`${job.packet.blockNumber} · ${short(job.packet.blockHash)}`],["Payload hash",job.packet.payloadHash],["Encoded payload",job.packet.encodedPayloadHash]])text(packet,label,value);
  const checks=document.querySelector("#verification-details");checks.replaceChildren();if(!job.verifications?.length){const empty=document.createElement("p");empty.className="empty";empty.textContent="No independent provider verification recorded.";checks.append(empty)}else for(const check of job.verifications){const card=document.createElement("div"),name=document.createElement("strong"),confirmations=document.createElement("b"),hash=document.createElement("small");name.textContent=check.provider;confirmations.textContent=`${check.confirmations} confirmations`;hash.textContent=`Block ${short(check.blockHash)} · payload ${short(check.payloadHash)}`;card.append(name,confirmations,hash);checks.append(card)}
  const policy=document.querySelector("#policy-details");policy.replaceChildren();const result=job.result;if(result){for(const [label,value] of [["Decision",result.decision],["Reason",result.reasonCode],["Policy version",result.policyVersion],["Evidence digest",result.evidenceDigest],["Finalized",new Date(result.finalizedAt*1000).toLocaleString()]])text(policy,label,value)}else text(policy,"Decision",job.stage==="POLICY_PENDING"?"Awaiting finalized consensus":"Not requested");
  const signer=document.querySelector("#signer-details");signer.replaceChildren();const count=job.signers?.length??0,summary=document.createElement("p"),meter=document.createElement("div");summary.className="quorum";summary.textContent=`${count} of 3 target signatures recorded`;meter.className="meter";meter.setAttribute("aria-label",`${count} of 3 signatures`);for(let i=0;i<3;i++){const segment=document.createElement("i");if(i<count)segment.className="filled";meter.append(segment)}signer.append(summary,meter);for(const address of job.signers??[]){const item=document.createElement("code");item.textContent=address;signer.append(item)}}
function render(job){renderTimeline(job);renderInspector(job);status.textContent=job.stage;status.className=`status ${job.stage==="REJECTED"?"bad":"live"}`;notice.textContent=`Live coordinator state · GUID ${short(job.packet.guid)}`}
function populate(){const prior=selectedGuid,observed=jobs.find(job=>job.packet.guid.toLowerCase()===observedGuid);select.replaceChildren(...jobs.map(job=>{const option=document.createElement("option");option.value=job.packet.guid;option.textContent=`${short(job.packet.guid)} · ${job.stage}`;return option}));select.disabled=false;selectedGuid=observed?.packet.guid??(jobs.some(job=>job.packet.guid===prior)?prior:jobs.at(-1).packet.guid);select.value=selectedGuid;render(jobs.find(job=>job.packet.guid===selectedGuid))}
function unavailable(message){timeline.replaceChildren();inspector.hidden=true;select.disabled=true;status.textContent="COORDINATOR UNAVAILABLE";status.className="status bad";notice.textContent=message}
async function refresh(){try{const response=await fetch("/api/jobs",{headers:{accept:"application/json"},cache:"no-store"});if(!response.ok)throw new Error(`status ${response.status}`);jobs=await response.json();if(!Array.isArray(jobs))throw new Error("invalid response");refreshed.textContent=`Refreshed ${new Date().toLocaleTimeString()}`;if(jobs.length===0){timeline.replaceChildren();inspector.hidden=true;select.disabled=true;status.textContent="NO PACKETS DETECTED";status.className="status";notice.textContent="Coordinator connected. No packet jobs exist.";return}populate()}catch(error){unavailable(`No coordinator data: ${error.message}. No simulated state is shown.`)}}
const deadLetters=document.querySelector("#dead-letters"),quarantineStatus=document.querySelector("#quarantine-status"),deliveries=document.querySelector("#deliveries"),deliveryStatus=document.querySelector("#delivery-status");
async function refreshDeadLetters(){try{const response=await fetch("/api/dead-letters",{headers:{accept:"application/json"},cache:"no-store"});if(!response.ok)throw new Error(`status ${response.status}`);const records=await response.json();if(!Array.isArray(records))throw new Error("invalid response");deadLetters.replaceChildren();quarantineStatus.textContent=records.length?`${records.length} QUARANTINED`:"CLEAR";quarantineStatus.className=`status ${records.length?"bad":"live"}`;if(!records.length){const empty=document.createElement("p");empty.className="empty";empty.textContent="No packets are durably quarantined.";deadLetters.append(empty);return}for(const record of records){const row=document.createElement("div");row.className="dead-letter";for(const value of[short(record.transactionHash),`Block ${record.blockNumber}`,`${record.attempts} attempts`,record.errorCode,new Date(record.lastFailedAt*1000).toLocaleString()]){const cell=document.createElement("span");cell.textContent=String(value);row.append(cell)}deadLetters.append(row)}}catch(error){quarantineStatus.textContent="UNAVAILABLE";quarantineStatus.className="status bad";deadLetters.replaceChildren();const message=document.createElement("p");message.className="empty";message.textContent=`No quarantine data: ${error.message}.`;deadLetters.append(message)}}
const deliveryDescriptions={SIGNING:"intent durable; collecting 3-of-5",READY:"quorum durable; awaiting submission",ATTEMPTING:"broadcast outcome pending",SUBMITTED:"awaiting independent confirmations",CONFIRMED:"verification independently confirmed",FAILED:"delivery failed",RECOVERY_REQUIRED:"operator reconciliation required"};
async function refreshDeliveries(){try{const response=await fetch("/api/deliveries",{headers:{accept:"application/json"},cache:"no-store"});if(!response.ok)throw new Error(`status ${response.status}`);const records=await response.json();if(!Array.isArray(records))throw new Error("invalid response");deliveryByGuid=new Map(records.filter(record=>typeof record.guid==="string").map(record=>[record.guid.toLowerCase(),record]));const selected=jobs.find(job=>job.packet.guid===selectedGuid);if(selected)render(selected);deliveries.replaceChildren();const incidents=records.filter(record=>record.state==="FAILED"||record.state==="RECOVERY_REQUIRED").length;deliveryStatus.textContent=incidents?`${incidents} INCIDENT${incidents===1?"":"S"}`:records.length?`${records.length} TRACKED`:"EMPTY";deliveryStatus.className=`status ${incidents?"bad":"live"}`;if(!records.length){const empty=document.createElement("p");empty.className="empty";empty.textContent="No destination deliveries have been prepared.";deliveries.append(empty);return}for(const record of records){const row=document.createElement("div");row.className=`delivery-row ${record.state==="FAILED"||record.state==="RECOVERY_REQUIRED"?"incident":""}`;for(const value of[short(record.guid),`${record.state} · ${deliveryDescriptions[record.state]??"unknown state"}`,short(record.transactionHash),record.confirmations?`${record.confirmations} confirmations`:"Not confirmed",record.failureCode??new Date(record.updatedAt*1000).toLocaleString()]){const cell=document.createElement("span");cell.textContent=String(value);row.append(cell)}deliveries.append(row)}}catch(error){deliveryStatus.textContent="UNAVAILABLE";deliveryStatus.className="status bad";deliveries.replaceChildren();const message=document.createElement("p");message.className="empty";message.textContent=`No delivery data: ${error.message}.`;deliveries.append(message)}}
async function refreshRuntime(){try{const response=await fetch("/health",{headers:{accept:"application/json"},cache:"no-store"});if(!response.ok)throw new Error(`status ${response.status}`);const value=await response.json();if(value?.presentationMode==="LOCAL_TEST")runtimeMode.textContent="LOCAL TEST";else if(value?.presentationMode==="EXTERNAL_INJECTED")runtimeMode.textContent="EXTERNAL INJECTED";else throw new Error("invalid mode")}catch{runtimeMode.textContent="MODE UNAVAILABLE"}}
select.addEventListener("change",()=>{observedGuid=undefined;selectedGuid=select.value;const job=jobs.find(item=>item.packet.guid===selectedGuid);if(job)render(job)});
window.addEventListener("sentinel:guid-observed",event=>{const guid=event.detail?.guid;if(typeof guid!=="string"||!/^0x[0-9a-fA-F]{64}$/.test(guid))return;observedGuid=guid.toLowerCase();const job=jobs.find(item=>item.packet.guid.toLowerCase()===observedGuid);if(job){selectedGuid=job.packet.guid;select.value=selectedGuid;render(job)}});
refreshRuntime();refresh();refreshDeadLetters();refreshDeliveries();setInterval(refreshRuntime,5000);setInterval(refresh,5000);setInterval(refreshDeadLetters,5000);setInterval(refreshDeliveries,5000);
