import type{Hex}from"../../../packages/core/src/types.js";import type{DestinationConfirmationVerifier}from"./destination-verifier.js";import type{VerificationOutboxStore,OutboxRecord}from"./verification-outbox.js";
export interface DestinationAdapterSubmitter{used(digest:Hex):Promise<boolean>;submitVerification(envelope:OutboxRecord["envelope"],signatures:Hex[]):Promise<Hex>;}
export interface ExecutionConfirmer{confirmExecution(guid:string):Promise<void>;}
export class DestinationWorker{
 constructor(private outbox:VerificationOutboxStore,private adapter:DestinationAdapterSubmitter,private verifier:DestinationConfirmationVerifier,private coordinator:ExecutionConfirmer,private clock=()=>Math.floor(Date.now()/1000)){}
 async pollOnce():Promise<number>{let processed=0;for(const record of await this.outbox.list()){if(record.state==="READY"){processed++;await this.submit(record)}else if(record.state==="ATTEMPTING"){processed++;await this.outbox.transition(record.guid,"ATTEMPTING",{state:"RECOVERY_REQUIRED",failureCode:"SUBMISSION_AMBIGUOUS",updatedAt:this.clock()})}else if(record.state==="SUBMITTED"){processed++;await this.confirm(record)}else if(record.state==="CONFIRMED"){await this.coordinator.confirmExecution(record.guid)}}return processed}
 private async submit(record:OutboxRecord):Promise<void>{if(await this.adapter.used(record.digest)){await this.outbox.transition(record.guid,"READY",{state:"RECOVERY_REQUIRED",failureCode:"USED_WITHOUT_RECEIPT",updatedAt:this.clock()});return}await this.outbox.transition(record.guid,"READY",{state:"ATTEMPTING",updatedAt:this.clock()});try{const transactionHash=await this.adapter.submitVerification(record.envelope,record.shares.map(share=>share.signature));await this.outbox.transition(record.guid,"ATTEMPTING",{state:"SUBMITTED",transactionHash,updatedAt:this.clock()})}catch{await this.outbox.transition(record.guid,"ATTEMPTING",{state:"RECOVERY_REQUIRED",failureCode:"SUBMISSION_AMBIGUOUS",updatedAt:this.clock()})}}
 private async confirm(record:OutboxRecord):Promise<void>{const result=await this.verifier.confirm(record);if(result.status==="PENDING")return;if(result.status==="FAILED"){await this.outbox.transition(record.guid,"SUBMITTED",{state:"FAILED",failureCode:result.code,transactionHash:record.transactionHash,updatedAt:this.clock()});return}await this.outbox.transition(record.guid,"SUBMITTED",{state:"CONFIRMED",transactionHash:record.transactionHash,confirmations:result.confirmations,updatedAt:this.clock()});await this.coordinator.confirmExecution(record.guid)}
}
