import{DatabaseSync}from"node:sqlite";import type{DetectedPacket}from"./listener.js";
export type FailureDisposition="RETRY"|"DEAD";
export interface DeadLetter{transactionHash:string;blockNumber:bigint;attempts:number;errorCode:string;firstFailedAt:number;lastFailedAt:number;}
export interface RecoverableDeadLetter extends DeadLetter{packet:DetectedPacket;}
export interface RecoveryStore{recordFailure(pathwayKey:string,packet:DetectedPacket,errorCode:string,now:number,maximumAttempts:number):Promise<FailureDisposition>;listDead(pathwayKey:string):Promise<DeadLetter[]>;findDead(pathwayKey:string,transactionHash:string):Promise<RecoverableDeadLetter|undefined>;resolve(pathwayKey:string,transactionHash:string):Promise<void>;close():void;}
interface Row{transaction_hash:string;packet_json:string;block_number:string;attempts:number;error_code:string;first_failed_at:number;last_failed_at:number;status:string;}
export class SqliteRecoveryStore implements RecoveryStore{
 private db:DatabaseSync;
 constructor(path:string){this.db=new DatabaseSync(path);this.db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; CREATE TABLE IF NOT EXISTS ingestion_failures(pathway_key TEXT NOT NULL,transaction_hash TEXT NOT NULL,packet_json TEXT NOT NULL,block_number TEXT NOT NULL,attempts INTEGER NOT NULL,error_code TEXT NOT NULL,first_failed_at INTEGER NOT NULL,last_failed_at INTEGER NOT NULL,status TEXT NOT NULL CHECK(status IN ('ACTIVE','DEAD')),PRIMARY KEY(pathway_key,transaction_hash)); CREATE INDEX IF NOT EXISTS ingestion_failures_dead ON ingestion_failures(pathway_key,status,last_failed_at);")}
 async recordFailure(pathwayKey:string,packet:DetectedPacket,errorCode:string,now:number,maximumAttempts:number):Promise<FailureDisposition>{if(!Number.isSafeInteger(maximumAttempts)||maximumAttempts<=0)throw new Error("maximum attempts must be a positive integer");if(!/^[A-Z][A-Z0-9_]{1,63}$/.test(errorCode))throw new Error("invalid error code");if(!Number.isSafeInteger(now)||now<0)throw new Error("invalid failure timestamp");const tx=normalizeHash(packet.transactionHash);this.db.exec("BEGIN IMMEDIATE");try{const prior=this.db.prepare("SELECT attempts,status FROM ingestion_failures WHERE pathway_key=? AND transaction_hash=?").get(pathwayKey,tx)as{attempts:number;status:string}|undefined;if(prior?.status==="DEAD"){this.db.exec("COMMIT");return"DEAD"}const attempts=(prior?.attempts??0)+1,status=attempts>=maximumAttempts?"DEAD":"ACTIVE";this.db.prepare("INSERT INTO ingestion_failures(pathway_key,transaction_hash,packet_json,block_number,attempts,error_code,first_failed_at,last_failed_at,status) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(pathway_key,transaction_hash) DO UPDATE SET packet_json=excluded.packet_json,block_number=excluded.block_number,attempts=excluded.attempts,error_code=excluded.error_code,last_failed_at=excluded.last_failed_at,status=excluded.status").run(pathwayKey,tx,encode(packet),packet.blockNumber.toString(),attempts,errorCode,now,now,status);this.db.exec("COMMIT");return status==="DEAD"?"DEAD":"RETRY"}catch(error){this.db.exec("ROLLBACK");throw error}}
 async listDead(pathwayKey:string):Promise<DeadLetter[]>{const rows=this.db.prepare("SELECT transaction_hash,block_number,attempts,error_code,first_failed_at,last_failed_at FROM ingestion_failures WHERE pathway_key=? AND status='DEAD' ORDER BY last_failed_at,transaction_hash").all(pathwayKey)as Array<Omit<Row,"packet_json"|"status">>;return rows.map(row=>({transactionHash:row.transaction_hash,blockNumber:BigInt(row.block_number),attempts:row.attempts,errorCode:row.error_code,firstFailedAt:row.first_failed_at,lastFailedAt:row.last_failed_at}))}
 async findDead(pathwayKey:string,transactionHash:string):Promise<RecoverableDeadLetter|undefined>{const row=this.db.prepare("SELECT transaction_hash,packet_json,block_number,attempts,error_code,first_failed_at,last_failed_at,status FROM ingestion_failures WHERE pathway_key=? AND transaction_hash=? AND status='DEAD'").get(pathwayKey,normalizeHash(transactionHash))as Row|undefined;return row?{transactionHash:row.transaction_hash,blockNumber:BigInt(row.block_number),attempts:row.attempts,errorCode:row.error_code,firstFailedAt:row.first_failed_at,lastFailedAt:row.last_failed_at,packet:decode(row.packet_json)as DetectedPacket}:undefined}
 async resolve(pathwayKey:string,transactionHash:string):Promise<void>{this.db.prepare("DELETE FROM ingestion_failures WHERE pathway_key=? AND transaction_hash=? AND status='DEAD'").run(pathwayKey,normalizeHash(transactionHash))}
 close():void{this.db.close()}
}
function normalizeHash(value:string):string{if(!/^0x[0-9a-fA-F]{64}$/.test(value))throw new Error("invalid transaction hash");return value.toLowerCase()}
function encode(value:unknown):string{return JSON.stringify(value,(_,item)=>typeof item==="bigint"?{$sentinelBigInt:item.toString()}:item)}
function decode(value:string):unknown{return JSON.parse(value,(_,item)=>item&&typeof item==="object"&&Object.keys(item).length===1&&typeof item.$sentinelBigInt==="string"?BigInt(item.$sentinelBigInt):item)}
