import{timingSafeEqual}from"node:crypto";import{isIP}from"node:net";import{getBytes,verifyMessage}from"ethers";import type{Hex}from"../../../packages/core/src/types.js";import{executionDigest,type SignatureShare,type SignerService,type SigningAuthorization,type SigningEnvelope}from"./signing.js";import{decodeSignerResponse,encodeSignerRequest,SIGNER_PROTOCOL_VERSION,type SignerRequest}from"./signer-protocol.js";
export interface AuthenticatedTransportResponse{status:number;body:string;authenticatedPeerSpkiSha256:Hex;}
export interface AuthenticatedSignerTransport{post(url:string,body:string,expectedPeerSpkiSha256:Hex):Promise<AuthenticatedTransportResponse>;}
export interface RemoteSignerConfig{url:string;address:Hex;peerSpkiSha256:Hex;coordinatorId:string;requestTtlSeconds:number;}
export class RemoteSignerClient implements SignerService{
 readonly address:Hex;private url:string;
 constructor(private config:RemoteSignerConfig,private transport:AuthenticatedSignerTransport,private requestId:()=>Hex,private clock=()=>Math.floor(Date.now()/1000)){this.url=endpoint(config.url);this.address=address(config.address);fingerprint(config.peerSpkiSha256);if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(config.coordinatorId))throw new Error("invalid coordinator ID");if(!Number.isSafeInteger(config.requestTtlSeconds)||config.requestTtlSeconds<=0)throw new Error("invalid request TTL")}
 async sign(envelope:SigningEnvelope,authorization:SigningAuthorization):Promise<SignatureShare>{const now=this.clock(),request:SignerRequest={version:SIGNER_PROTOCOL_VERSION,requestId:this.requestId(),coordinatorId:this.config.coordinatorId,issuedAt:now,expiresAt:now+this.config.requestTtlSeconds,envelope,authorization},body=encodeSignerRequest(request);let reply:AuthenticatedTransportResponse;try{reply=await this.transport.post(this.url,body,this.config.peerSpkiSha256)}catch{throw new Error("remote signer unavailable")}if(!sameFingerprint(reply.authenticatedPeerSpkiSha256,this.config.peerSpkiSha256))throw new Error("remote signer authentication failed");if(reply.status!==200)throw new Error("remote signer refused request");let response;try{response=decodeSignerResponse(reply.body)}catch{throw new Error("invalid remote signer response")}const digest=executionDigest(envelope);if(response.requestId!==request.requestId||response.signer!==this.address||response.digest!==digest)throw new Error("remote signer response binding mismatch");if(verifyMessage(getBytes(digest),response.signature).toLowerCase()!==this.address)throw new Error("invalid remote signer signature");return{address:this.address,digest,signature:response.signature}}
}
function endpoint(value:string):string{let url:URL;try{url=new URL(value)}catch{throw new Error("invalid signer endpoint")}if(url.protocol!=="https:"||url.username||url.password||url.port||url.hostname==="localhost"||url.hostname.endsWith(".localhost")||isIP(url.hostname.replace(/^\[|\]$/g,""))!==0)throw new Error("signer endpoint must be public HTTPS");return url.href}
function address(value:string):Hex{if(!/^0x[0-9a-f]{40}$/.test(value)||/^0x0{40}$/.test(value))throw new Error("invalid signer address");return value as Hex}
function fingerprint(value:string):Buffer{if(!/^0x[0-9a-f]{64}$/.test(value))throw new Error("invalid signer SPKI fingerprint");return Buffer.from(value.slice(2),"hex")}
function sameFingerprint(left:string,right:string):boolean{try{return timingSafeEqual(fingerprint(left),fingerprint(right))}catch{return false}}
