import{timingSafeEqual}from"node:crypto";import{executionDigest,type IsolatedSignerService}from"./signing.js";import{decodeSignerRequest,encodeSignerResponse,responseFromShare,signerAuthorizationHash,SIGNER_PROTOCOL_VERSION}from"./signer-protocol.js";import type{SignerReplayStore}from"./signer-replay-store.js";
type ErrorCode="AUTHENTICATION_FAILED"|"INVALID_REQUEST"|"REQUEST_EXPIRED"|"REPLAYED_REQUEST"|"CONFLICTING_REQUEST"|"SIGNING_REFUSED";
export interface ProtocolReply{status:number;body:string;}
export class SignerProtocolHandler{
 constructor(private signer:IsolatedSignerService,private replay:SignerReplayStore,private allowed:{coordinatorId:string;coordinatorSpkiSha256:string;maxRequestTtlSeconds:number},private clock=()=>Math.floor(Date.now()/1000)){if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(allowed.coordinatorId))throw new Error("invalid coordinator ID");fingerprint(allowed.coordinatorSpkiSha256);if(!Number.isSafeInteger(allowed.maxRequestTtlSeconds)||allowed.maxRequestTtlSeconds<=0)throw new Error("invalid maximum request TTL")}
 async handle(authenticatedPeerSpki:string,body:string):Promise<ProtocolReply>{if(!sameFingerprint(authenticatedPeerSpki,this.allowed.coordinatorSpkiSha256))return failure(401,"AUTHENTICATION_FAILED");let request;try{request=decodeSignerRequest(body)}catch{return failure(400,"INVALID_REQUEST")}if(request.coordinatorId!==this.allowed.coordinatorId)return failure(401,"AUTHENTICATION_FAILED");const now=this.clock();if(request.issuedAt>now||request.expiresAt-request.issuedAt>this.allowed.maxRequestTtlSeconds)return failure(400,"INVALID_REQUEST");if(request.expiresAt<=now)return failure(409,"REQUEST_EXPIRED");let disposition;try{disposition=await this.replay.reserve(request.coordinatorId,request.requestId,request.envelope.guid,executionDigest(request.envelope),signerAuthorizationHash(request.authorization),request.expiresAt,now)}catch{return failure(500,"SIGNING_REFUSED")}if(disposition==="DUPLICATE")return failure(409,"REPLAYED_REQUEST");if(disposition==="CONFLICT")return failure(409,"CONFLICTING_REQUEST");try{const share=await this.signer.sign(request.envelope,request.authorization);return{status:200,body:encodeSignerResponse(responseFromShare(request.requestId,share))}}catch{return failure(403,"SIGNING_REFUSED")}}
}
function failure(status:number,code:ErrorCode):ProtocolReply{return{status,body:JSON.stringify({version:SIGNER_PROTOCOL_VERSION,error:{code,message:"request refused"}})}}
function fingerprint(value:string):Buffer{if(!/^0x[0-9a-f]{64}$/.test(value))throw new Error("invalid SPKI fingerprint");return Buffer.from(value.slice(2),"hex")}
function sameFingerprint(left:string,right:string):boolean{try{return timingSafeEqual(fingerprint(left),fingerprint(right))}catch{return false}}
