import http from "node:http";
import{readFile}from"node:fs/promises";import{join,resolve}from"node:path";
import type {Coordinator} from "./coordinator.js";
import type{DeadLetterReader}from"./recovery-service.js";
import type{OutboxRecord}from"./verification-outbox.js";
import type{RecoveryReceiptReader}from"./recovery-audit.js";
import{publicRuntimeStatus,type RuntimeStatusReader}from"./runtime-observation.js";
import{publicDemoCapability,type DemoCapability}from"./demo-capability.js";
export interface DeliveryStatusRecord extends OutboxRecord {executionFailureCode?:string;}
export interface DeliveryReader{list():Promise<DeliveryStatusRecord[]>;}
export interface RuntimePresentation{presentationMode:"LOCAL_TEST"|"EXTERNAL_INJECTED";}
const localPresentation:RuntimePresentation={presentationMode:"LOCAL_TEST"};

export interface StatusResponse {status:number;body:string;}
export async function statusResponse(coordinator:Coordinator,method:string,path:string,deadLetters?:DeadLetterReader,deliveries?:DeliveryReader,presentation:RuntimePresentation=localPresentation,demo?:DemoCapability,recoveryActions?:RecoveryReceiptReader,runtimeStatus?:RuntimeStatusReader):Promise<StatusResponse> {
  if(method!=="GET")return{status:405,body:json({error:"method not allowed"})};
  const url=new URL(path,"http://localhost");if(url.pathname==="/health")return{status:200,body:json({status:"ok",mode:"testnet-prototype",presentationMode:presentation.presentationMode})};
  if(url.pathname==="/api/demo/config")return demo?{status:200,body:json(publicDemoCapability(demo))}:{status:404,body:json({error:"demo capability unavailable"})};
  if(url.pathname==="/api/runtime-status"){if(!runtimeStatus)return{status:503,body:json({error:"runtime status unavailable"})};try{return{status:200,body:json(publicRuntimeStatus(runtimeStatus.runtimeStatus()))}}catch{return{status:503,body:json({error:"runtime status unavailable"})}}}
  if(url.pathname==="/api/jobs")return{status:200,body:json([...coordinator.jobs.values()].map(j=>j.snapshot))};
  if(url.pathname==="/api/dead-letters"){const records=deadLetters?await deadLetters.listDead():[];return{status:200,body:json(records.map(record=>({transactionHash:record.transactionHash,blockNumber:record.blockNumber,attempts:record.attempts,errorCode:record.errorCode,firstFailedAt:record.firstFailedAt,lastFailedAt:record.lastFailedAt})))}};
  if(url.pathname==="/api/deliveries"){const records=deliveries?await deliveries.list():[];return{status:200,body:json(records.map(record=>({guid:record.guid,digest:record.digest,state:record.state,transactionHash:record.transactionHash,confirmations:record.confirmations,failureCode:record.failureCode,executionFailureCode:record.executionFailureCode,createdAt:record.createdAt,updatedAt:record.updatedAt})))}};
  if(url.pathname==="/api/recovery-actions"){const records=recoveryActions?await recoveryActions.listRecoveryReceipts():[];return{status:200,body:json(records.map(record=>({actionId:record.actionId,kind:record.kind,subject:record.subject,candidateTransactionHash:record.candidateTransactionHash,operators:record.operators,approvalCount:record.approvalCount,preparedAt:record.preparedAt,executeAfter:record.executeAfter,expiresAt:record.expiresAt,appliedAt:record.appliedAt,resultCode:record.resultCode,previousReceiptHash:record.previousReceiptHash,receiptHash:record.receiptHash})))}};
  const match=url.pathname.match(/^\/api\/jobs\/(0x[0-9a-fA-F]{64})$/);if(match){const job=coordinator.jobs.get(match[1]!);return job?{status:200,body:json(job.snapshot)}:{status:404,body:json({error:"job not found"})}}
  return{status:404,body:json({error:"not found"})};
}
export function createStatusServer(coordinator:Coordinator,deadLetters?:DeadLetterReader,deliveries?:DeliveryReader,presentation:RuntimePresentation=localPresentation,demo?:DemoCapability,recoveryActions?:RecoveryReceiptReader,runtimeStatus?:RuntimeStatusReader):http.Server{return http.createServer(async(req,res)=>{const value=await statusResponse(coordinator,req.method??"GET",req.url??"/",deadLetters,deliveries,presentation,demo,recoveryActions,runtimeStatus);res.statusCode=value.status;res.setHeader("content-type","application/json; charset=utf-8");res.setHeader("cache-control","no-store");res.setHeader("x-content-type-options","nosniff");res.end(value.body)})}
export interface AppResponse {status:number;body:string|Uint8Array;contentType:string;}
const assets=new Map([["/",["index.html","text/html; charset=utf-8"]],["/src/app.js",["src/app.js","text/javascript; charset=utf-8"]],["/src/timeline.js",["src/timeline.js","text/javascript; charset=utf-8"]],["/src/runtime-status.js",["src/runtime-status.js","text/javascript; charset=utf-8"]],["/src/pathway-audit.js",["src/pathway-audit.js","text/javascript; charset=utf-8"]],["/src/hero-motion.js",["src/hero-motion.js","text/javascript; charset=utf-8"]],["/src/style.css",["src/style.css","text/css; charset=utf-8"]],["/src/recovery.css",["src/recovery.css","text/css; charset=utf-8"]],["/src/delivery.css",["src/delivery.css","text/css; charset=utf-8"]],["/src/demo.css",["src/demo.css","text/css; charset=utf-8"]],["/assets/sentinel-network-loop.mp4",["assets/sentinel-network-loop.mp4","video/mp4"]],["/assets/sentinel-network-poster.jpg",["assets/sentinel-network-poster.jpg","image/jpeg"]],["/assets/geist-latin.woff2",["assets/geist-latin.woff2","font/woff2"]],["/assets/special-elite-latin.woff2",["assets/special-elite-latin.woff2","font/woff2"]]] as const);
export async function dashboardResponse(coordinator:Coordinator,method:string,path:string,root:string,deadLetters?:DeadLetterReader,deliveries?:DeliveryReader,presentation:RuntimePresentation=localPresentation,demo?:DemoCapability,recoveryActions?:RecoveryReceiptReader,runtimeStatus?:RuntimeStatusReader):Promise<AppResponse>{const url=new URL(path,"http://localhost");if(url.pathname==="/health"||url.pathname.startsWith("/api/")){const value=await statusResponse(coordinator,method,path,deadLetters,deliveries,presentation,demo,recoveryActions,runtimeStatus);return{...value,contentType:"application/json; charset=utf-8"}}if(method!=="GET")return{status:405,body:json({error:"method not allowed"}),contentType:"application/json; charset=utf-8"};if(url.pathname==="/assets/demo.js")return{status:200,body:await readFile(resolve(root,"../../dist/apps/dashboard/demo.js")),contentType:"text/javascript; charset=utf-8"};const asset=assets.get(url.pathname as "/"|"/src/app.js"|"/src/timeline.js"|"/src/runtime-status.js"|"/src/pathway-audit.js"|"/src/hero-motion.js"|"/src/style.css"|"/src/recovery.css"|"/src/delivery.css"|"/src/demo.css"|"/assets/sentinel-network-loop.mp4"|"/assets/sentinel-network-poster.jpg"|"/assets/geist-latin.woff2"|"/assets/special-elite-latin.woff2");if(!asset)return{status:404,body:json({error:"not found"}),contentType:"application/json; charset=utf-8"};return{status:200,body:await readFile(join(root,asset[0])),contentType:asset[1]}}
export function createDashboardServer(coordinator:Coordinator,root:string,deadLetters?:DeadLetterReader,deliveries?:DeliveryReader,presentation:RuntimePresentation=localPresentation,demo?:DemoCapability,recoveryActions?:RecoveryReceiptReader,runtimeStatus?:RuntimeStatusReader):http.Server{return http.createServer(async(req,res)=>{try{const value=await dashboardResponse(coordinator,req.method??"GET",req.url??"/",root,deadLetters,deliveries,presentation,demo,recoveryActions,runtimeStatus);res.statusCode=value.status;headers(res,value.contentType);res.end(value.body)}catch{res.statusCode=500;headers(res,"application/json; charset=utf-8");res.end(json({error:"dashboard asset unavailable"}))}})}
function headers(res:http.ServerResponse,contentType:string):void{res.setHeader("content-type",contentType);res.setHeader("cache-control","no-store");res.setHeader("x-content-type-options","nosniff");res.setHeader("referrer-policy","no-referrer");res.setHeader("permissions-policy","camera=(), microphone=(), geolocation=()");res.setHeader("content-security-policy","default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self'; font-src 'self'; media-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'")}
function json(value:unknown):string{return JSON.stringify(value,(_,v)=>typeof v==="bigint"?v.toString():v)}
