import{DatabaseSync}from"node:sqlite";import type{Hex}from"../../../packages/core/src/types.js";import{executionDigest,type SignatureShare,type SigningEnvelope}from"./signing.js";
export type OutboxState="READY"|"ATTEMPTING"|"SUBMITTED"|"CONFIRMED"|"FAILED"|"RECOVERY_REQUIRED";
export interface OutboxRecord{guid:Hex;digest:Hex;envelope:SigningEnvelope;shares:SignatureShare[];state:OutboxState;transactionHash?:Hex;confirmations?:bigint;failureCode?:string;createdAt:number;updatedAt:number;}
export interface OutboxUpdate{state:OutboxState;transactionHash?:Hex;confirmations?:bigint;failureCode?:string;updatedAt:number;}
export interface VerificationOutboxStore{prepare(guid:Hex,envelope:SigningEnvelope,shares:SignatureShare[],now:number):Promise<OutboxRecord>;transition(guid:Hex,expected:OutboxState,update:OutboxUpdate):Promise<OutboxRecord>;get(guid:Hex):Promise<OutboxRecord|undefined>;list():Promise<OutboxRecord[]>;close():void;}
const allowed:Record<OutboxState,OutboxState[]>={READY:["ATTEMPTING","CONFIRMED","FAILED","RECOVERY_REQUIRED"],ATTEMPTING:["SUBMITTED","CONFIRMED","RECOVERY_REQUIRED"],SUBMITTED:["CONFIRMED","FAILED"],CONFIRMED:[],FAILED:[],RECOVERY_REQUIRED:[]};
export class SqliteVerificationOutbox implements VerificationOutboxStore{
 private db:DatabaseSync;
 constructor(path:string){this.db=new DatabaseSync(path);this.db.exec("PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; CREATE TABLE IF NOT EXISTS verification_outbox(guid TEXT PRIMARY KEY,state TEXT NOT NULL,record_json TEXT NOT NULL,updated_at INTEGER NOT NULL);")}
 async prepare(guid:Hex,envelope:SigningEnvelope,shares:SignatureShare[],now:number):Promise<OutboxRecord>{validateTime(now);const normalized=validatePayload(guid,envelope,shares),record:OutboxRecord={...normalized,state:"READY",createdAt:now,updatedAt:now};this.db.exec("BEGIN IMMEDIATE");try{const prior=this.db.prepare("SELECT record_json FROM verification_outbox WHERE guid=?").get(guid)as{record_json:string}|undefined;if(prior){const existing=decode(prior.record_json);if(payload(existing)!==payload(record))throw new Error("outbox preparation conflict");this.db.exec("COMMIT");return existing}this.db.prepare("INSERT INTO verification_outbox(guid,state,record_json,updated_at) VALUES(?,?,?,?)").run(guid,"READY",encode(record),now);this.db.exec("COMMIT");return record}catch(error){this.db.exec("ROLLBACK");throw error}}
 async transition(guid:Hex,expected:OutboxState,update:OutboxUpdate):Promise<OutboxRecord>{validateHash(guid,"GUID");validateTime(update.updatedAt);this.db.exec("BEGIN IMMEDIATE");try{const row=this.db.prepare("SELECT state,record_json FROM verification_outbox WHERE guid=?").get(guid)as{state:OutboxState;record_json:string}|undefined;if(!row)throw new Error("unknown outbox GUID");if(row.state!==expected)throw new Error("outbox state mismatch");if(!allowed[expected].includes(update.state))throw new Error("invalid outbox transition");const current=decode(row.record_json),next={...current,...update};validateUpdate(next);this.db.prepare("UPDATE verification_outbox SET state=?,record_json=?,updated_at=? WHERE guid=? AND state=?").run(next.state,encode(next),next.updatedAt,guid,expected);this.db.exec("COMMIT");return next}catch(error){this.db.exec("ROLLBACK");throw error}}
 async get(guid:Hex):Promise<OutboxRecord|undefined>{validateHash(guid,"GUID");const row=this.db.prepare("SELECT record_json FROM verification_outbox WHERE guid=?").get(guid)as{record_json:string}|undefined;return row?decode(row.record_json):undefined}
 async list():Promise<OutboxRecord[]>{return(this.db.prepare("SELECT record_json FROM verification_outbox ORDER BY updated_at,guid").all()as Array<{record_json:string}>).map(row=>decode(row.record_json))}
 close():void{this.db.close()}
}
function validatePayload(guid:Hex,envelope:SigningEnvelope,shares:SignatureShare[]):Pick<OutboxRecord,"guid"|"digest"|"envelope"|"shares">{validateHash(guid,"GUID");if(envelope.guid!==guid)throw new Error("outbox GUID mismatch");const digest=executionDigest(envelope);if(!shares.length)throw new Error("outbox shares required");let prior="";for(const share of shares){const address=share.address.toLowerCase();if(!/^0x[0-9a-f]{40}$/.test(address)||address<=prior)throw new Error("outbox shares must be unique and sorted");if(share.digest.toLowerCase()!==digest)throw new Error("outbox share digest mismatch");if(!/^0x[0-9a-fA-F]{130}$/.test(share.signature))throw new Error("invalid outbox signature");prior=address}return{guid,digest,envelope,shares}}
function validateUpdate(record:OutboxRecord):void{if(record.updatedAt<record.createdAt)throw new Error("invalid outbox timestamp");if(record.state==="SUBMITTED"&&!record.transactionHash)throw new Error("submitted outbox requires transaction hash");if(record.transactionHash)validateHash(record.transactionHash,"transaction hash");if(record.state==="CONFIRMED"&&(!record.confirmations||record.confirmations<=0n))throw new Error("confirmed outbox requires confirmations");if(record.failureCode&&!/^[A-Z][A-Z0-9_]{1,63}$/.test(record.failureCode))throw new Error("invalid outbox failure code")}
function payload(record:OutboxRecord):string{return encode({guid:record.guid,digest:record.digest,envelope:record.envelope,shares:record.shares})}
function validateHash(value:string,name:string):void{if(!/^0x[0-9a-f]{64}$/.test(value))throw new Error(`invalid ${name}`)}function validateTime(value:number):void{if(!Number.isSafeInteger(value)||value<0)throw new Error("invalid outbox timestamp")}
function encode(value:unknown):string{return JSON.stringify(value,(_,item)=>typeof item==="bigint"?{$sentinelBigInt:item.toString()}:item)}function decode(value:string):OutboxRecord{return JSON.parse(value,(_,item)=>item&&typeof item==="object"&&Object.keys(item).length===1&&typeof item.$sentinelBigInt==="string"?BigInt(item.$sentinelBigInt):item)as OutboxRecord}
